import type { Metadata } from "next";
import { Figtree, Geist, Geist_Mono, Urbanist } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const figtree = Figtree({
  subsets: ['latin'],
  display: 'swap',
  variable: "--font-figtree",
})

const urbanist = Urbanist({
  subsets: ['latin'],
  display: 'swap',
  variable: "--font-urbanist",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${figtree.variable} ${urbanist.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
